services:
  app:
    build: .
    image: app-dev
    command: npm run dev
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./code/server/logs/:/src/code/server/logs/:z
      - ./benchmarks/:/src/benchmarks/:z
      - ./dist/:/src/dist/:z
      - .:/src/:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - nodemodules:/src/node_modules
      # We want the content of shared output dir for CCs to be empty
      - type: volume
        source: cc-output
        target: /src/bin/output/
        volume:
          nocopy: true

volumes:
  nodemodules: {}
  cc-output: {}
