export const FOREGROUND = 'var(--cForeground)'
export const BACKGROUND = 'var(--cBackground)'
export const FONT = 'var(--cFont)'
export const FONT_INVERSE = 'var(--cFontInverse)'

export const PEACH_PRIMARY = 'var(--cPeachPrimary)'
export const PEACH_SECONDARY = 'var(--cPeachSecondary)'
export const ACCENT_PRIMARY = 'var(--cAccentPrimary)'
export const ACCENT_SECONDARY = 'var(--cAccentSecondary)'

export const DARK_PRIMARY = 'var(--cDarkPrimary)'
export const DARK_SECONDARY = 'var(--cDarkSecondary)'
export const GREEN_PRIMARY = 'var(--cGreenPrimary)'
export const GREEN_SECONDARY = 'var(--cGreenSecondary)'
export const CYAN_PRIMARY = 'var(--cCyanPrimary)'
export const CYAN_SECONDARY = 'var(--cCyanSecondary)'
export const BLUE_PRIMARY = 'var(--cBluePrimary)'
export const BLUE_SECONDARY = 'var(--cBlueSecondary)'
export const PURPLE_PRIMARY = 'var(--cPurplePrimary)'
export const PURPLE_SECONDARY = 'var(--cPurpleSecondary)'
export const ORANGE_PRIMARY = 'var(--cOrangePrimary)'
export const ORANGE_SECONDARY = 'var(--cOrangeSecondary)'
