name: CI

on:
  # Triggers the workflow on push or pull request events for the selected branches
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      # Includes configuration to cache installed moduels to improve build time
      - uses: c-hive/gha-npm-cache@v1

      - name: Restore packages
        run: npm install

      - name: Execute linter
        run: npm run lint

      - name: Run Mocha tests
        run: npm run mocha

  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2
      # Includes configuration to cache installed moduels to improve build time
      - uses: c-hive/gha-npm-cache@v1

      - name: Restore packages
        run: npm install

      - name: Produce production webpack bundle
        run: npm run build
